// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUmi2uy_l2ygJpgqWrR287KnBUQtwKGHE',
    appId: '1:1083430098079:web:a0af69bb7ab8712a90feaa',
    messagingSenderId: '1083430098079',
    projectId: 'flutterfire-dear-diary',
    authDomain: 'flutterfire-dear-diary.firebaseapp.com',
    storageBucket: 'flutterfire-dear-diary.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA81KTH5J3g_7G00Ur743pXhZa1_wPwmjI',
    appId: '1:1083430098079:android:e2230d2a683e46dc90feaa',
    messagingSenderId: '1083430098079',
    projectId: 'flutterfire-dear-diary',
    storageBucket: 'flutterfire-dear-diary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpnnx84cl0tzUTN32isaBUMbyfFlC8MHY',
    appId: '1:1083430098079:ios:0cb0d892b2edd35990feaa',
    messagingSenderId: '1083430098079',
    projectId: 'flutterfire-dear-diary',
    storageBucket: 'flutterfire-dear-diary.appspot.com',
    iosBundleId: 'com.example.dearDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpnnx84cl0tzUTN32isaBUMbyfFlC8MHY',
    appId: '1:1083430098079:ios:17f791372390e1a690feaa',
    messagingSenderId: '1083430098079',
    projectId: 'flutterfire-dear-diary',
    storageBucket: 'flutterfire-dear-diary.appspot.com',
    iosBundleId: 'com.example.dearDiary.RunnerTests',
  );
}
